imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@SCUserBundle/Resources/config/services.yml' }
    - { resource: '@SCProviderBundle/Resources/config/services.yml' }
    - { resource: '@SCAdminBundle/Resources/config/sonata.yml' }
    - { resource: '@SCAdminBundle/Resources/config/services.yml' }

framework:
    #esi:             ~
    trusted_proxies: ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        google_maps_api_key: %google_maps_api_key%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        #unix_socket:	/var/mysql/mysql.sock
        types:
            point: SC\CommonBundle\DBAL\Types\PointType
            datetime: SC\CommonBundle\DBAL\Types\UTCDateTimeType
        mapping_types:
            point: string
    orm:
        dql:
            numeric_functions:
                              ACOS: DoctrineExtensions\Query\Mysql\Acos
                              SIN: DoctrineExtensions\Query\Mysql\Sin
                              RADIANS: DoctrineExtensions\Query\Mysql\Radians
                              COS: DoctrineExtensions\Query\Mysql\Cos
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: SC\UserBundle\Entity\User
    registration:
        form:
            type: sc_user_registration
            handler: sc.form.handler.registration
    profile:
        form:
            type: sc_user_profile
            handler: sc.form.handler.profile

jms_serializer:
    metadata:
        cache: apc
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/serializer/FOSUB

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            uploadable: true

services:
    # -- Common bundle --
    sc.tokenservice:
        class: SC\CommonBundle\Extension\TokenService
        arguments:
            - "@service_container"
    sc.form.type.token_input_entity:
        class: SC\CommonBundle\Form\Type\TokenInputEntityType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator"
        tags:
            - { name: form.type, alias: token_input_entity }
    # -- Site bundle --
    authentication_handler:
          class: SC\SiteBundle\Extension\AuthenticationHandler
          arguments:
              - "@service_container"
          tags:
              - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
              - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }